//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СитекWPF.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDR_OBJ
    {
        public int ID { get; set; }
        public Nullable<long> OBJECTID { get; set; }
        public string OBJECTGUID { get; set; }
        public Nullable<long> CHANGEID { get; set; }
        public string NAME { get; set; }
        public string TYPENAME { get; set; }
        public Nullable<int> LEVEL { get; set; }
        public Nullable<int> OPERTYPEID { get; set; }
        public Nullable<int> PREVID { get; set; }
        public Nullable<int> NEXTID { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<int> ISACTUAL { get; set; }
        public Nullable<int> ISACTIVE { get; set; }
    
        public virtual AS_OBJECT_LEVELS AS_OBJECT_LEVELS { get; set; }
    }
}
